apiVersion: v1
kind: Pod
metadata:
  name: audit-pod
  labels:
    app: audit-pod
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: audit.json
  containers:
  - name: test-seccomp
    image: nginx:alpine
    securityContext:
      allowPrivilegeEscalation: false
